development:
  google_client_id:     'Put Google client id'
  google_client_secret: 'Put Google client secret'
  coin_market_cap_key:  'Coin market cap key'

production:
  google_client_id:     'Put Google client id'
  google_client_secret: 'Put Google client secret'
  coin_market_cap_key:  'Coin market cap key'