development:
  google_client_id:     '489099783130-kr0fm0nkitmmifjkpb6cnlj5lgvueee4.apps.googleusercontent.com'
  google_client_secret: 'Y6pyML0pH5JLqu1MNCWG63oI'
  coin_market_cap_key:  '8c2c0788-597c-4442-81fe-2fa0c8780e32'